name: windows-docker
on: push
jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: &workdir 'D:\a\.pyenv\'
    steps:
      - name: create working-directory
        run: set -x; mkdir -p "$workdir"; echo $PWD
        working-directory: 'C:\'
        env: { workdir: *workdir }
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: *workdir 
        
