name: windows-docker
on: push
jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    env:
      HOME: D:\a\.pyenv
      PYENV: D:\a\.pyenv\pyenv-win
      PYENV_HOME: D:\a\.pyenv\pyenv-win
    steps:
      - name: create working-directory
        run: |
            mkdir -p '${{ env.HOME }}'
      - name: checkout
        run: |
            git clone https://github.com/pyenv-win/pyenv-win.git '${{ env.HOME }}'
#         uses: actions/checkout@v2
#         with:
#           path: ..\..\.pyenv
      - name: pyenv update, install
        run: | 
            ${{ env.PYENV }}\bin\pyenv.bat --version
            ${{ env.PYENV }}\bin\pyenv.bat update
            ${{ env.PYENV }}\bin\pyenv.bat install 3.7.4
            
            
      - name: pyenv set global
        run: |
            ${{ env.PYENV }}\bin\pyenv.bat global 3.7.4
            ${{ env.PYENV }}\bin\pyenv.bat versions
            ${{ env.PYENV }}\shims\python --version
            
      - name: pytest pre-req
        run: |
            ${{ env.PYENV }}\shims\pip install -r requirements_dev.txt
            ${{ env.PYENV }}\bin\pyenv.bat rehash
      - name: pytest
        run: |
            PYTHONPATH=${{ env.PYENV }} ${{ env.PYENV }}\bin\python -m pytest -v -s tests
